"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from config import Config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = Config.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = Config.DEBUG

# Public hostnames plus `server`, the name web (SSR) and ws use on the internal Docker network.
ALLOWED_HOSTS = [*Config.ALLOWED_HOSTS, *Config.INTERNAL_HOSTS]

CSRF_TRUSTED_ORIGINS = Config.CSRF_TRUSTED_ORIGINS

# CORS: only the web frontend's origins, only for the API, with cookies (the JWT) allowed.
# Server-to-server calls (ws, web SSR) have no Origin header and aren't affected by CORS.
CORS_ALLOWED_ORIGINS = Config.CORS_ALLOWED_ORIGINS
CORS_ALLOW_CREDENTIALS = True
CORS_URLS_REGEX = r'^/api/.*$'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'authenticator',
    'canvas',
]

MIDDLEWARE = [
    # First, so CORS headers are added to every response (including errors and preflights).
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = Config.DATABASES


# JWT (shared with ws/), read via django.conf.settings in your auth decorators

JWT_SECRET = Config.JWT_SECRET
JWT_ALGORITHM = Config.JWT_ALGORITHM
JWT_ISSUER = Config.JWT_ISSUER
JWT_AUDIENCE = Config.JWT_AUDIENCE
JWT_ACCESS_COOKIE = Config.JWT_ACCESS_COOKIE
JWT_ACCESS_TTL_MINUTES = Config.JWT_ACCESS_TTL_MINUTES
JWT_REFRESH_TTL_DAYS = Config.JWT_REFRESH_TTL_DAYS
JWT_COOKIE_SECURE = Config.JWT_COOKIE_SECURE


# Login brute-force protection (authenticator/views.py)

LOGIN_MAX_FAILURES = Config.LOGIN_MAX_FAILURES
LOGIN_LOCKOUT_MINUTES = Config.LOGIN_LOCKOUT_MINUTES


# Cache: redis in Docker (shared by all workers), in-memory otherwise

CACHES = {
    'default': (
        {'BACKEND': 'django.core.cache.backends.redis.RedisCache', 'LOCATION': Config.CACHE_URL}
        if Config.CACHE_URL
        else {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}
    )
}


# Canvas (game library) API: requests per user per minute (canvas/views.py)

CANVAS_REQUESTS_PER_MINUTE = Config.CANVAS_REQUESTS_PER_MINUTE
# Game documents can embed assets as base64, so allow request bodies up to the gateway's
# 10 MB (proxy/nginx.conf client_max_body_size). Django's default is 2.5 MB.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024


# Password / username recovery (authenticator/views.py)

FRONTEND_URL = Config.FRONTEND_URL
PASSWORD_RESET_MINUTES = Config.PASSWORD_RESET_MINUTES


# Email

# DEMO_EMAIL=1 saves emails to the demo inbox instead of sending them (authenticator/email_backends.py).
DEMO_EMAIL = Config.DEMO_EMAIL
EMAIL_BACKEND = 'authenticator.email_backends.DemoInboxBackend' if DEMO_EMAIL else Config.EMAIL_BACKEND
EMAIL_HOST = Config.EMAIL_HOST
EMAIL_PORT = Config.EMAIL_PORT
EMAIL_HOST_USER = Config.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = Config.EMAIL_HOST_PASSWORD
EMAIL_USE_TLS = Config.EMAIL_USE_TLS
DEFAULT_FROM_EMAIL = Config.DEFAULT_FROM_EMAIL


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
