#!/bin/sh
set -eu

for package in engine scripting web; do
  target="/app/$package/node_modules"
  source="/opt/dependencies/$package"
  if ! cmp -s "$source/.image-stamp" "$target/.image-stamp"; then
    echo "$package: node_modules volume is older than the image; refreshing it"
    find "$target" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
    cp -a "$source/." "$target/"
  fi
done

# The dev bind mount hides assets generated by npm ci in the image.
# Recreate them from the installed package before preparing the editor.
(cd /app/scripting && node scripts/copy-pyodide.mjs)

exec npm run dev -- --hostname 0.0.0.0 --port "${PORT:-3000}"
