import { cp, mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const web = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const root = resolve(web, "..");
for (const name of ["engine", "scripting"]) {
  if (!process.env.npm_execpath)
    throw new Error("Run this script with npm run prepare:editor.");
  execFileSync(process.execPath, [process.env.npm_execpath, "run", "build"], {
    cwd: resolve(root, name),
    stdio: "inherit",
  });
}
const target = resolve(web, "public/runtime");
await mkdir(target, { recursive: true });
for (const name of ["rive.wasm", "rive_fallback.wasm"]) {
  await cp(resolve(web, "node_modules/@rive-app/canvas", name), resolve(target, name));
}
await cp(
  resolve(root, "scripting/public/pyodide"),
  resolve(target, "pyodide"),
  { recursive: true },
);
await cp(
  resolve(
    root,
    "engine/node_modules/@babylonjs/havok/lib/esm/HavokPhysics.wasm",
  ),
  resolve(target, "HavokPhysics.wasm"),
);
const assets = resolve(root, "scripting/dist/assets");
const worker = (await readdir(assets)).find((name) =>
  /^worker-.*\.js$/.test(name),
);
if (!worker) throw new Error("Build did not produce a scripting worker.");
await cp(resolve(assets, worker), resolve(target, "worker.js"));
await writeFile(
  resolve(target, "README.txt"),
  "Generated by npm run prepare:editor. Do not edit.\n",
);
console.log("Editor runtime assets ready.");
await import("./build-public-player.mjs");
