#!/usr/bin/env python3
"""Bark production operations. Run on the VM; all subprocess arguments are literal.

Secrets live outside Git in /etc/bark/production.env. OCI uses instance principals.
No command provisions resources, upgrades an account, or restores over production.
"""
import argparse
from contextlib import contextmanager
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess
import sys
import time
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = Path('/etc/bark/production.env')
STATE = Path('/var/lib/bark')
SERVICES = {'caddy', 'proxy', 'web', 'server', 'ws', 'db', 'redis'}
MAX_STORAGE = 9 * 1024**3  # Headroom below the 10 GB Standard tier during the trial.


def run(args, **kwargs):
    # Never include a subprocess's command/env in exception output (may contain credentials).
    result = subprocess.run([str(x) for x in args], check=False, **kwargs)
    if result.returncode:
        raise RuntimeError(f'{args[0]} failed (exit {result.returncode}); see service logs')
    return result


def read_env(path=ENV_FILE):
    values = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        key, sep, value = line.partition('=')
        if not sep or not re.fullmatch(r'[A-Z][A-Z0-9_]*', key):
            raise ValueError('Invalid production environment file')
        values[key] = value
    for key in ('SITE_DOMAIN', 'ACME_EMAIL', 'POSTGRES_PASSWORD', 'DJANGO_SECRET_KEY',
                'JWT_SECRET', 'OCI_REGION', 'OCI_NAMESPACE', 'OCI_BUCKET', 'OCI_TOPIC_ID'):
        if not values.get(key) or values[key] == 'change-me':
            raise ValueError(f'Missing production value: {key}')
    validate_domain(values['SITE_DOMAIN'])
    for key in ('POSTGRES_PASSWORD', 'DJANGO_SECRET_KEY', 'JWT_SECRET'):
        if not re.fullmatch(r'[A-Za-z0-9_-]{43,}', values[key]):
            raise ValueError(f'{key} must be generated by init')
    return values


def validate_domain(domain):
    if not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.duckdns\.org', domain):
        raise ValueError('Use your registered lowercase DuckDNS hostname')


def release_sha(value):
    if not re.fullmatch(r'[0-9a-f]{40}', value):
        raise ValueError('Release must be a full 40-character Git commit SHA')
    return value


def read_state():
    path = STATE / 'release.json'
    return json.loads(path.read_text()) if path.exists() else {}


def save_state(value):
    STATE.mkdir(parents=True, exist_ok=True, mode=0o700)
    temporary = STATE / 'release.tmp'
    temporary.write_text(json.dumps(value, indent=2) + '\n')
    temporary.replace(STATE / 'release.json')


@contextmanager
def operation_lock():
    import fcntl
    STATE.mkdir(parents=True, exist_ok=True, mode=0o700)
    with (STATE / 'operations.lock').open('w') as handle:
        fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
        yield


class Production:
    def __init__(self, sha=None):
        self.env = read_env()
        state = read_state()
        self.sha = release_sha(sha or state.get('active') or state.get('pending', {}).get('sha', ''))

    def compose(self, *args, **kwargs):
        # Avoid ambient shell variables silently overriding the reviewed production settings.
        env = {k: v for k, v in os.environ.items() if not k.startswith(('BARK_', 'COMPOSE_', 'DOCKER_'))}
        env.update(self.env, BARK_RELEASE=self.sha, BARK_PLATFORM='linux/arm64')
        return run(['docker', 'compose', '--project-directory', ROOT, '--env-file', ENV_FILE,
                    '-f', ROOT / 'docker-compose.prod.yml', *args], env=env, **kwargs)

    def oci(self, *args):
        result = run(['oci', '--auth', 'instance_principal', '--region', self.env['OCI_REGION'],
                      *args, '--output', 'json'], capture_output=True, text=True)
        return json.loads(result.stdout) if result.stdout.strip() else {}

    def objects(self):
        return self.oci('os', 'object', 'list', '--namespace-name', self.env['OCI_NAMESPACE'],
                        '--bucket-name', self.env['OCI_BUCKET'], '--all').get('data') or []

    def check_bucket(self):
        bucket = self.oci('os', 'bucket', 'get', '--namespace-name', self.env['OCI_NAMESPACE'],
                          '--bucket-name', self.env['OCI_BUCKET'])['data']
        if bucket['public-access-type'] != 'NoPublicAccess' or bucket.get('versioning') not in (None, 'Disabled'):
            raise RuntimeError('Backups require a private bucket with versioning disabled')

    def alert(self, message):
        self.oci('ons', 'message', 'publish', '--topic-id', self.env['OCI_TOPIC_ID'],
                 '--title', 'Bark hosting', '--body', message)

    def backup(self, category='daily'):
        self.check_bucket()
        stamp = datetime.now(timezone.utc).strftime('%Y-%m-%d' if category == 'daily' else '%Y-%m-%dT%H%M%SZ')
        name = f'{category}/{stamp}.dump'
        target = STATE / 'backups' / name
        target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        temporary = target.with_suffix('.partial')
        with temporary.open('wb') as output:
            self.compose('exec', '-T', 'db', 'pg_dump', '-U', 'bark', '-d', 'bark',
                         '--format=custom', '--no-owner', '--no-acl', stdout=output)
        if temporary.stat().st_size == 0:
            raise RuntimeError('Empty database backup')
        with temporary.open('rb') as backup_input:
            self.compose('exec', '-T', 'db', 'pg_restore', '--list', stdin=backup_input,
                         stdout=subprocess.DEVNULL)
        objects = self.objects()
        projected = sum(item['size'] for item in objects if item['name'] != name) + temporary.stat().st_size
        if projected > MAX_STORAGE:
            raise RuntimeError('Backup upload would exceed the 9 GiB storage budget; retain existing backups')
        self.oci('os', 'object', 'put', '--namespace-name', self.env['OCI_NAMESPACE'],
                 '--bucket-name', self.env['OCI_BUCKET'], '--name', name, '--file', str(temporary),
                 '--storage-tier', 'Standard', '--force')
        temporary.replace(target)
        # Retention only applies to our exact backup names, after a successful upload.
        pattern = r'daily/\d{4}-\d{2}-\d{2}\.dump' if category == 'daily' else r'predeploy/\d{4}-\d{2}-\d{2}T\d{6}Z\.dump'
        names = sorted({item['name'] for item in objects if re.fullmatch(pattern, item['name'])} | {name})
        keep = 7 if category == 'daily' else 2
        for old in names[:-keep]:
            self.oci('os', 'object', 'delete', '--namespace-name', self.env['OCI_NAMESPACE'],
                     '--bucket-name', self.env['OCI_BUCKET'], '--name', old, '--force')
            local = STATE / 'backups' / old
            if local.exists():
                local.unlink()
        (STATE / 'backup-success').write_text(str(time.time()))
        if projected > MAX_STORAGE * .8:
            self.alert('Backup storage has passed 80% of the 9 GiB budget. Review capacity.')
        return target

    def build(self):
        actual = run(['git', '-C', ROOT, 'rev-parse', 'HEAD'], capture_output=True, text=True).stdout.strip()
        dirty = run(['git', '-C', ROOT, 'status', '--porcelain'], capture_output=True, text=True).stdout.strip()
        if actual != self.sha or dirty:
            raise RuntimeError('Build requires a clean checkout at the requested release SHA')
        architecture = run(['docker', 'info', '--format', '{{.Architecture}}'], capture_output=True, text=True).stdout.strip()
        if architecture not in ('aarch64', 'arm64'):
            raise RuntimeError('Build production releases on the Oracle ARM64 VM')
        self.compose('config', '--quiet')
        self.compose('build', 'web', 'server', 'ws', 'proxy')
        for service in ('web', 'server', 'ws', 'proxy'):
            arch = run(['docker', 'image', 'inspect', f'bark-{service}:{self.sha}', '--format', '{{.Architecture}}'],
                       capture_output=True, text=True).stdout.strip()
            if arch != 'arm64':
                raise RuntimeError(f'{service} is not ARM64')
        state = read_state()
        state['built'] = self.sha
        save_state(state)

    def prepare(self):
        state = read_state()
        if state.get('built') != self.sha:
            raise RuntimeError('Build this release first')
        if state.get('pending') and state['pending']['sha'] != self.sha:
            raise RuntimeError('Resolve the pending deployment before preparing another release')
        if state.get('pending', {}).get('digest'):
            raise RuntimeError('A valid pending backup already exists; copy it and resume activate')
        self.check_bucket()
        self.compose('up', '-d', '--wait', '--wait-timeout', '120', 'db', 'redis')
        # Record intent before stopping anything, so failures never look like a healthy release.
        state['pending'] = {'sha': self.sha}
        save_state(state)
        self.compose('stop', 'caddy', 'proxy', 'web', 'server', 'ws')
        backup = self.backup('predeploy')
        with backup.open('rb') as source:
            digest = hashlib.file_digest(source, 'sha256').hexdigest()
        state['pending'].update(backup=str(backup), digest=digest)
        save_state(state)
        # Path/hash are safe to show; the contents are never printed.
        print(json.dumps({'backup': str(backup), 'sha256': digest}))

    def activate(self, copied_digest):
        state = read_state()
        pending = state.get('pending', {})
        if pending.get('sha') != self.sha or not secrets.compare_digest(pending.get('digest', ''), copied_digest):
            raise RuntimeError('Copy the pending backup off the VM and pass its verified SHA256')
        self.compose('run', '--rm', '--no-deps', 'server', 'python', 'manage.py', 'migrate', '--noinput')
        self.compose('run', '--rm', '--no-deps', 'server', 'python', 'manage.py', 'collectstatic', '--noinput', '--clear')
        self.compose('up', '-d', '--no-build', '--wait', '--wait-timeout', '180')
        # ACME may take a little longer than container startup. Never disable TLS validation.
        for attempt in range(12):
            try:
                for path in ('/', '/healthz', '/static/admin/css/base.css'):
                    with urllib.request.urlopen(f'https://{self.env["SITE_DOMAIN"]}{path}', timeout=10) as response:
                        if response.status != 200:
                            raise RuntimeError('Public readiness failed')
                break
            except Exception:
                if attempt == 11:
                    raise RuntimeError('Public HTTPS readiness failed; pending deployment retained')
                time.sleep(5)
        save_state({'active': self.sha, 'previous': state.get('active'), 'built': self.sha})
        print(f'Release {self.sha} is serving HTTPS. Run browser acceptance checks next.')

    def monitor(self):
        problems = []
        if read_state().get('pending'):
            problems.append('A deployment is pending; traffic may be stopped.')
        result = self.compose('ps', '--all', '--format', 'json', capture_output=True, text=True)
        raw = result.stdout.strip()
        containers = json.loads(raw) if raw.startswith('[') else [json.loads(line) for line in raw.splitlines() if line]
        healthy = {x['Service'] for x in containers if x['State'] == 'running' and x.get('Health') in ('', 'healthy')}
        if SERVICES - healthy:
            problems.append('Unhealthy or missing services: ' + ', '.join(sorted(SERVICES - healthy)))
        disk = shutil.disk_usage(STATE)
        if disk.free / disk.total < .2:
            problems.append('Disk free space is below 20%.')
        marker = STATE / 'backup-success'
        if not marker.exists() or time.time() - float(marker.read_text()) > 26 * 3600:
            problems.append('No successful backup in the last 26 hours.')
        if sum(item['size'] for item in self.objects()) > MAX_STORAGE * .8:
            problems.append('Backup storage exceeds 80% of its budget.')
        try:
            with urllib.request.urlopen(f'https://{self.env["SITE_DOMAIN"]}/healthz', timeout=10):
                pass
        except Exception:
            problems.append('Public HTTPS/API readiness is failing.')
        signature = '\n'.join(problems)
        alert_file = STATE / 'last-alert'
        previous = alert_file.read_text() if alert_file.exists() else ''
        if signature != previous:
            self.alert(signature or 'Bark services and backups have recovered.')
            alert_file.write_text(signature)
        if problems:
            print(signature, file=sys.stderr)

    def restore_check(self, backup):
        # Always uses a NEW database, never the production database.
        name = 'bark_restore_' + secrets.token_hex(6)
        self.compose('exec', '-T', 'db', 'createdb', '-U', 'bark', name)
        try:
            with Path(backup).open('rb') as source:
                self.compose('exec', '-T', 'db', 'pg_restore', '-U', 'bark', '-d', name,
                             '--no-owner', '--no-acl', '--exit-on-error', stdin=source)
            self.compose('run', '--rm', '--no-deps', '-e', f'POSTGRES_DB={name}',
                         'server', 'python', 'manage.py', 'check', '--database', 'default')
            self.compose('exec', '-T', 'db', 'psql', '-U', 'bark', '-d', name, '-v', 'ON_ERROR_STOP=1',
                         '-c', 'SELECT count(*) AS saved_games FROM canvas_game;')
            print('Restore succeeded in an isolated database. Browser reopening still needs the staging stack.')
        finally:
            self.compose('exec', '-T', 'db', 'dropdb', '-U', 'bark', name)


def initialize(args):
    validate_domain(args.domain)
    supplied = {'SITE_DOMAIN': args.domain, 'ACME_EMAIL': args.email, 'OCI_REGION': args.region,
                'OCI_NAMESPACE': args.namespace, 'OCI_BUCKET': args.bucket, 'OCI_TOPIC_ID': args.topic}
    if any(not re.fullmatch(r'[A-Za-z0-9@._+-]+', value) for value in supplied.values()):
        raise ValueError('Invalid configuration value')
    ENV_FILE.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    for key in ('POSTGRES_PASSWORD', 'DJANGO_SECRET_KEY', 'JWT_SECRET'):
        supplied[key] = secrets.token_urlsafe(48)
    # Never rotate an existing database password/secret implicitly.
    with ENV_FILE.open('x') as output:
        os.chmod(ENV_FILE, 0o600)
        output.write(''.join(f'{key}={value}\n' for key, value in supplied.items()))
    print('Production settings and fresh secrets written to /etc/bark/production.env')


def main():
    os.umask(0o077)
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest='command', required=True)
    init = commands.add_parser('init')
    for key in ('domain', 'email', 'namespace', 'bucket', 'topic', 'region'):
        init.add_argument('--' + key, required=True)
    for name in ('build', 'prepare'):
        commands.add_parser(name).add_argument('sha', type=release_sha)
    activate = commands.add_parser('activate')
    activate.add_argument('sha', type=release_sha)
    activate.add_argument('--copied-backup-sha256', required=True)
    for name in ('backup', 'monitor', 'status', 'test-alert'):
        commands.add_parser(name)
    restore = commands.add_parser('restore-check')
    restore.add_argument('backup')
    args = parser.parse_args()
    production = None
    try:
        if args.command == 'init':
            initialize(args)
            return
        if args.command == 'status':
            print(json.dumps(read_state(), indent=2))
            return
        production = Production(getattr(args, 'sha', None))
        with operation_lock():
            if args.command == 'activate':
                production.activate(args.copied_backup_sha256)
            elif args.command == 'restore-check':
                production.restore_check(args.backup)
            elif args.command == 'test-alert':
                production.alert('Bark hosting alerts are configured. Confirm you received this message.')
            else:
                getattr(production, args.command)()
    except BlockingIOError:
        print('Another deployment or backup is running; try again after it completes.', file=sys.stderr)
        sys.exit(1)
    except Exception as error:
        print(f'{args.command} failed: {error}', file=sys.stderr)
        if production:
            try:
                # A broken monitor/OCI connection must not flood the free email quota.
                marker = STATE / f'{args.command}-failure-alert'
                if not marker.exists() or time.time() - marker.stat().st_mtime > 24 * 3600:
                    production.alert(f'Bark {args.command} failed. Check the VM journal; deployment state has been preserved.')
                    marker.touch()
            except Exception:
                print('Alert delivery also failed. Check OCI permissions and the notification subscription.', file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
