# Generated by Django 6.1.1 on 2026-09-26 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0002_demoemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('document_version', models.PositiveSmallIntegerField(default=1)),
                ('project_version', models.PositiveSmallIntegerField(default=1)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('project_extra', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='authenticator.user', to_field='user_id')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GameCameras',
            fields=[
                ('data', models.JSONField(default=dict)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cameras', serialize=False, to='canvas.game')),
            ],
            options={
                'db_table': 'canvas_game_cameras',
            },
        ),
        migrations.CreateModel(
            name='GameInput',
            fields=[
                ('data', models.JSONField(default=dict)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='input', serialize=False, to='canvas.game')),
            ],
            options={
                'db_table': 'canvas_game_input',
            },
        ),
        migrations.CreateModel(
            name='GameScript',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='script', serialize=False, to='canvas.game')),
                ('language', models.CharField(choices=[('python', 'Python'), ('blocks', 'Blocks')], default='python', max_length=16)),
                ('source', models.TextField(blank=True, default='')),
                ('workspace', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'canvas_game_script',
            },
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('data', models.JSONField(default=dict)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='canvas.game')),
            ],
            options={
                'db_table': 'canvas_game_settings',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transform', models.JSONField(default=dict)),
                ('visual', models.JSONField(blank=True, null=True)),
                ('collider', models.JSONField(blank=True, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('character', models.JSONField(blank=True, null=True)),
                ('interaction', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='canvas.game')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'db_table': 'canvas_entity',
                'ordering': ['position'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('game', 'item_id'), name='canvas_entity_unique_id')],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='canvas.game')),
            ],
            options={
                'db_table': 'canvas_asset',
                'ordering': ['position'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('game', 'item_id'), name='canvas_asset_unique_id')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='canvas.game')),
            ],
            options={
                'db_table': 'canvas_material',
                'ordering': ['position'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('game', 'item_id'), name='canvas_material_unique_id')],
            },
        ),
        migrations.CreateModel(
            name='Prefab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefabs', to='canvas.game')),
            ],
            options={
                'db_table': 'canvas_prefab',
                'ordering': ['position'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('game', 'item_id'), name='canvas_prefab_unique_id')],
            },
        ),
    ]
