# Generated by Django 6.1.1 on 2026-09-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_demoemail'),
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='collaboration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='invite_code',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WorkspaceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=256)),
                ('user_id', models.CharField(max_length=132)),
                ('connection', models.UUIDField()),
                ('expires_at', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='canvas.game')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'resource'), name='workspace_lock_unique')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='canvas.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.user', to_field='user_id')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'user'), name='workspace_member_unique')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('commit_id', models.UUIDField()),
                ('user_id', models.CharField(max_length=132)),
                ('connection', models.UUIDField()),
                ('ops', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='canvas.game')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'revision'), name='workspace_revision_unique'), models.UniqueConstraint(fields=('game', 'commit_id'), name='workspace_commit_unique')],
            },
        ),
    ]
